### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: '/path/to/venv/lib/python3.8/site-packages/hybrid_django_react/copy_assets.py/../assets

### ISSUE THREAD

**Issue by lluc2397** [gmso/hybrid-django-react#5]
I've run the pip install and then the create-django-react-app. After entering information i get the following error:

Django project name [django_project]: 
Django project description [Awesome project]: 
Author's name [author]: 
Author's email [author@mail.com]: 
Software license [MIT License]: 

  ■ Copying assets

Traceback (most recent call last):
  File "/path/to/venv/bin/create-django-react-app", line 8, in <module>
    sys.exit(main())
  File "/path/to/venv/lib/python3.8/site-packages/hybrid_django_react/run.py", line 43, in main
    copy_assets_to_current_dir()
  File "/path/to/venv/lib/python3.8/site-packages/hybrid_django_react/copy_assets.py", line 8, in copy_assets_to_current_dir
    files = os.listdir(assets_path)
NotADirectoryError: [Errno 20] Not a directory: '/path/to/venv/lib/python3.8/site-packages/hybrid_django_react/copy_assets.py/../assets'

**Comment by gmso** [comment]
Hi,

can you please share your systems specifications? From your error message I assume you're using Python 3.8, but what about OS, pip version, which version of this library you are using, etc. ?

Also, have you installed this library using a virtual environment? Could you please describe the steps you followed to get this error message? That could help pin down the problem. Thanks!

**Comment by lluc2397** [comment]
Hi sorry for the lack of information.

OS is Ubuntu 20.04.3 LTS, 
Python 3.8
PIP version 20.0.2
hybrid-django-react==0.2.1
virtualenv 20.0.17

I just followed the steps that you described in the Readme. I first created a virtualenv, then I downloaded with pip and finally I ran the comman create-django-react-app.
